spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

kogpt-api:
  host: "https://api.kakaobrain.com"
  endpoint: "/v1/inference/kogpt/generation"

logging:
  level:
    com.project.security.basic.feign: DEBUG